### ISSUE TITLE
Az idézőjelet nem tudja kezelni a cím

### ISSUE THREAD

**Issue by csiteibela** [hegyhati/psak_2020#6]
Delacasse Krisztina az érintett ("Becsületbeli ügy" - jogtörténeti példa egy virtuális szcenárióra).

**Comment by hegyhati** [comment]
@csiteibela  Majd meglesem, de ha elobb jutsz oda, probald ki, hogy escape-eled igy:
```
title : "\"Becsuletbeli ugy\" - jogtorteneti..."
```
Vagy az is lehet mukodik, hogy aposztrofok koze rakod az egeszet, es akkor azon belul idezojel.

(Es ha megoldja, akkor le is zarhatod az issue-t ;-) )

**Comment by csiteibela** [comment]
Az első megoldás működött. :) Nagyon köszönöm!
